language: python
python:
  - "2.7"
before_install:
    - pip install -U setuptools
    - sudo add-apt-repository -y ppa:pyside/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq libusb-dev python-pyside
    - ln -s /usr/lib/python2.7/dist-packages/PySide ~/virtualenv/python2.7/lib/python2.7/site-packages/
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install -r requirements-test.txt --use-mirrors
    - pip install .
script:  py.test --cov spreads --cov spreadsplug
after_success: coveralls
